/**
 * pdf-engine.js
 *
 * Reusable utility for generating production-quality PDFs across the DTECH platform.
 * Utilizes html2pdf.js for offline, client-side generation.
 */

/**
 * Generates a standard DTECH report PDF from a specific element.
 *
 * @param {Object} options Configuration options
 * @param {HTMLElement} options.element The DOM element containing the report content.
 * @param {string} options.filename The name of the output PDF file.
 * @param {string} [options.title='DTECH Report'] Title displayed at the top of the PDF.
 * @param {string} [options.orientation='portrait'] 'portrait' or 'landscape'
 * @param {number[]} [options.margin=[15, 15, 25, 15]] Margins [top, right, bottom, left]
 */
export async function generateDtechPDF(options) {
    const {
        element,
        filename,
        title = 'DTECH Eligibility Report',
        orientation = 'portrait',
        margin = [15, 15, 25, 15] // Extra bottom margin for footer
    } = options;

    if (!element) {
        console.error("No element provided to generateDtechPDF");
        return;
    }

    // 1. Clone the target element so we can safely modify it before printing
    const clone = element.cloneNode(true);

    // Create a hidden wrapper so html2pdf can render it properly
    const wrapper = document.createElement('div');
    wrapper.style.position = 'absolute';
    wrapper.style.top = '-9999px';
    wrapper.style.left = '-9999px';
    wrapper.style.width = '800px'; // fixed width for consistent rendering
    wrapper.style.backgroundColor = '#121212'; // DTECH dark theme background
    wrapper.style.color = '#ffffff';
    wrapper.style.padding = '20px';
    wrapper.style.fontFamily = 'Arial, sans-serif';

    // 2. Strip out unwanted elements (buttons, inputs, etc.)
    const excludeSelectors = ['button', 'input', 'select', '.hidden', 'svg.icon'];
    excludeSelectors.forEach(selector => {
        const els = clone.querySelectorAll(selector);
        els.forEach(el => el.remove());
    });

    // 3. Add Header
    const dateStr = new Date().toLocaleString();
    const header = document.createElement('div');
    header.style.borderBottom = '2px solid var(--primary-accent, #007bff)';
    header.style.marginBottom = '20px';
    header.style.paddingBottom = '10px';
    header.innerHTML = `
        <div style="display: flex; justify-content: space-between; align-items: flex-end;">
            <div>
                <h1 style="margin: 0; color: var(--primary-accent, #007bff); font-size: 24px; font-weight: bold;">D-TECH</h1>
                <h2 style="margin: 5px 0 0 0; font-size: 18px; color: #fff;">${title}</h2>
            </div>
            <div style="text-align: right; color: #aaa; font-size: 12px;">
                Generated on:<br>${dateStr}
            </div>
        </div>
    `;

    // 4. Assemble Wrapper
    wrapper.appendChild(header);
    wrapper.appendChild(clone);
    document.body.appendChild(wrapper);

    // 5. Configure html2pdf
    const opt = {
        margin: margin,
        filename: filename || 'DTECH_Report.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
            scale: 2,
            useCORS: true,
            backgroundColor: '#121212' // Ensure background is dark
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: orientation },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
        // html2pdf allows injecting custom JS into the jsPDF instance via the `toPdf` hook
        const worker = window.html2pdf().set(opt).from(wrapper);

        await worker.toPdf().get('pdf').then(function (pdf) {
            const totalPages = pdf.internal.getNumberOfPages();
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            for (let i = 1; i <= totalPages; i++) {
                pdf.setPage(i);

                pdf.setFontSize(8);
                pdf.setTextColor(150, 150, 150); // Light gray

                // Footer details
                const footerText1 = "Generated by DTECH Services. Empowering the youth through digital innovation.";
                const legalNote = "Disclaimer: This is an estimate based on official requirements from university prospectuses.";
                const pageNumberText = `Page ${i} of ${totalPages}`;

                // Positioning for footer
                const yPosition = pageHeight - 10;

                pdf.text(footerText1, pageWidth / 2, yPosition, { align: 'center' });
                pdf.text(legalNote, pageWidth / 2, yPosition + 4, { align: 'center' });
                pdf.text(pageNumberText, pageWidth - 15, yPosition + 4, { align: 'right' });

                // Add a line above footer
                pdf.setDrawColor(50, 50, 50);
                pdf.setLineWidth(0.5);
                pdf.line(15, yPosition - 4, pageWidth - 15, yPosition - 4);
            }
        });

        // Finalize and save
        await worker.save();
    } catch (e) {
        console.error("Error generating PDF:", e);
    } finally {
        // Clean up
        if (wrapper.parentNode) {
            wrapper.parentNode.removeChild(wrapper);
        }
    }
}
